INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (1000, 10, 'Ultimate');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (2000, 20, 'Sérénité');
INSERT INTO produit (ID, NUMERO_PRODUIT, LIBELLE) VALUES (3000, 30, 'Silver');